.PHONY: clean All

All:
	@echo "----------Building project:[ cl5 - Release ]----------"
	@cd "cl5" && "$(MAKE)" -f  "cl5.mk"
clean:
	@echo "----------Cleaning project:[ cl5 - Release ]----------"
	@cd "cl5" && "$(MAKE)" -f  "cl5.mk" clean
