.PHONY: clean All

All:
	@echo "----------Building project:[ alg5 - Debug ]----------"
	@cd "alg5" && "$(MAKE)" -f  "alg5.mk"
clean:
	@echo "----------Cleaning project:[ alg5 - Debug ]----------"
	@cd "alg5" && "$(MAKE)" -f  "alg5.mk" clean
