.PHONY: clean All

All:
	@echo "----------Building project:[ proba - Debug ]----------"
	@cd "proba" && "$(MAKE)" -f  "proba.mk"
clean:
	@echo "----------Cleaning project:[ proba - Debug ]----------"
	@cd "proba" && "$(MAKE)" -f  "proba.mk" clean
