.PHONY: clean All

All:
	@echo "----------Building project:[ OOO_MOYA_OBORONA - Debug ]----------"
	@cd "OOO_MOYA_OBORONA" && "$(MAKE)" -f  "OOO_MOYA_OBORONA.mk"
clean:
	@echo "----------Cleaning project:[ OOO_MOYA_OBORONA - Debug ]----------"
	@cd "OOO_MOYA_OBORONA" && "$(MAKE)" -f  "OOO_MOYA_OBORONA.mk" clean
