.PHONY: clean All

All:
	@echo "----------Building project:[ TableTest - Debug ]----------"
	@cd "TableTest" && "$(MAKE)" -f  "TableTest.mk"
clean:
	@echo "----------Cleaning project:[ TableTest - Debug ]----------"
	@cd "TableTest" && "$(MAKE)" -f  "TableTest.mk" clean
