.PHONY: clean All

All:
	@echo "----------Building project:[ vtoroy - Debug ]----------"
	@cd "vtoroy" && "$(MAKE)" -f  "vtoroy.mk"
clean:
	@echo "----------Cleaning project:[ vtoroy - Debug ]----------"
	@cd "vtoroy" && "$(MAKE)" -f  "vtoroy.mk" clean
