.PHONY: clean All

All:
	@echo "----------Building project:[ tree - Release ]----------"
	@cd "tree" && "$(MAKE)" -f  "tree.mk"
clean:
	@echo "----------Cleaning project:[ tree - Release ]----------"
	@cd "tree" && "$(MAKE)" -f  "tree.mk" clean
