.PHONY: clean All

All:
	@echo "----------Building project:[ Perestanovka - Debug ]----------"
	@cd "/home/asic27/Timp/Perestanovka" && "$(MAKE)" -f  "Perestanovka.mk"
clean:
	@echo "----------Cleaning project:[ Perestanovka - Debug ]----------"
	@cd "/home/asic27/Timp/Perestanovka" && "$(MAKE)" -f  "Perestanovka.mk" clean
