.PHONY: clean All

All:
	@echo "----------Building project:[ ls - Debug ]----------"
	@cd "ls" && "$(MAKE)" -f  "ls.mk"
clean:
	@echo "----------Cleaning project:[ ls - Debug ]----------"
	@cd "ls" && "$(MAKE)" -f  "ls.mk" clean
