.PHONY: clean All

All:
	@echo "----------Building project:[ cck - Debug ]----------"
	@cd "cck" && "$(MAKE)" -f  "cck.mk"
clean:
	@echo "----------Cleaning project:[ cck - Debug ]----------"
	@cd "cck" && "$(MAKE)" -f  "cck.mk" clean
