.PHONY: clean All

All:
	@echo "----------Building project:[ tri1 - Debug ]----------"
	@cd "tri1" && "$(MAKE)" -f  "tri1.mk"
clean:
	@echo "----------Cleaning project:[ tri1 - Debug ]----------"
	@cd "tri1" && "$(MAKE)" -f  "tri1.mk" clean
