.PHONY: clean All

All:
	@echo "----------Building project:[ zadanie4 - Debug ]----------"
	@cd "zadanie4" && "$(MAKE)" -f  "zadanie4.mk"
clean:
	@echo "----------Cleaning project:[ zadanie4 - Debug ]----------"
	@cd "zadanie4" && "$(MAKE)" -f  "zadanie4.mk" clean
